version: '3.8'
services:
  api-gateway:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - AUTH_SERVICE_URL=https://auth-service-production-efff.up.railway.app
      - AUCTION_SERVICE_URL=https://auction-service-production-0633.up.railway.app
      - BID_SERVICE_URL=https://bid-service-production.up.railway.app
      - CORS_DEBUG=true
      - ALLOWED_ORIGINS=https://subastas-mora.netlify.app,http://localhost:3000,http://localhost:5173
    # Remover env_file si no tienes .env
    # env_file:
    #   - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Agregar logging para debug
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
