services:
  - type: web
    name: api-gateway
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: docker build -t api-gateway .
    startCommand: docker run -p $PORT:$PORT api-gateway
    envVars:
      - key: NODE_ENV
        value: production
      - key: AUTH_SERVICE_URL
        value: https://auth-service-production-efff.up.railway.app
      - key: AUCTION_SERVICE_URL
        value: https://auction-service-production-0633.up.railway.app
      - key: BID_SERVICE_URL
        value: https://bid-service-production.up.railway.app
      - key: CORS_DEBUG
        value: "true"
      - key: ALLOWED_ORIGINS
        value: "https://subastas-mora.netlify.app,https://api-gateway-g9gb.onrender.com"
      - key: RENDER_EXTERNAL_URL
        value: "https://api-gateway-g9gb.onrender.com"
    healthCheckPath: /health
    autoDeploy: true
